namespace WinMux.Terminal;

/// <summary>
/// WinMux-owned surface over a VT terminal emulator.
/// </summary>
/// <remarks>
/// Implementations are expected to serialize access to their underlying parser. Responses are
/// raised synchronously while <see cref="Write"/> processes terminal output and must be sent back
/// to the PTY so terminal queries do not stall the child process.
/// </remarks>
public interface ITerminalEngine
{
    int Columns { get; }

    int Rows { get; }

    /// <summary>Number of history rows preceding the visible screen.</summary>
    int ScrollbackCount { get; }

    /// <summary>History and visible rows addressable by <see cref="CopyRow"/>.</summary>
    int TotalRows { get; }

    /// <summary>Monotonic grid-change counter for renderer damage tracking.</summary>
    long Version { get; }

    TerminalCursor Cursor { get; }

    string Title { get; }

    bool UsingAlternateScreen { get; }

    /// <summary>
    /// Whether the program asked (DECSET 1004) to be told when the terminal gains and loses focus,
    /// as <c>ESC [ I</c> and <c>ESC [ O</c>. Editors use it to reload files; Claude Code uses it to
    /// decide whether the user is away and a notification is worth sending.
    /// </summary>
    bool FocusReportingEnabled { get; }

    /// <summary>
    /// Whether the program asked (DECSET 2004) for pasted text to arrive between <c>ESC [ 200 ~</c>
    /// and <c>ESC [ 201 ~</c>, so that it can tell a paste from typing — and not run each line of a
    /// multi-line paste as it arrives.
    /// </summary>
    bool BracketedPasteEnabled { get; }

    /// <summary>
    /// DECCKM: the program asked for cursor keys as <c>ESC O A</c> rather than <c>ESC [ A</c>. Full-screen
    /// programs — vim, less — switch it on while they run.
    /// </summary>
    bool ApplicationCursorKeysEnabled { get; }

    /// <summary>
    /// Changes when OSC 8 link identifiers may have been renumbered or discarded.
    /// </summary>
    int HyperlinkGeneration { get; }

    /// <summary>Raised when the terminal grid changes.</summary>
    event Action? Updated;

    /// <summary>Raised when the terminal title changes.</summary>
    event Action<string>? TitleChanged;

    /// <summary>
    /// Raised when a cooperating shell reports its current directory through OSC 9;9 or OSC 7.
    /// Windows paths and POSIX/WSL paths retain their reported separator style.
    /// </summary>
    event Action<string>? WorkingDirectoryChanged;

    /// <summary>
    /// Bytes generated by terminal queries such as DA, DSR, and DECRQM. The subscriber must
    /// write them back to the PTY. The supplied memory must not be retained after the callback.
    /// </summary>
    event Action<ReadOnlyMemory<byte>>? Response;

    /// <summary>
    /// Raised when the program asks for the user's attention: an OSC 9, 777 or 99 notification, or a
    /// bare BEL. Raised on the thread that called <see cref="Write"/>, with the engine's lock held,
    /// so a subscriber must hand the work off rather than call back into the engine.
    /// </summary>
    event Action<TerminalNotification>? NotificationRequested;

    /// <summary>
    /// Raised when the program puts text on the clipboard with OSC 52. Raised under the engine's lock
    /// on the writing thread; the subscriber must marshal to whatever owns the clipboard.
    /// </summary>
    event Action<string>? ClipboardWriteRequested;

    /// <summary>Feeds bytes received from the PTY into the VT parser.</summary>
    void Write(ReadOnlySpan<byte> bytes);

    /// <summary>
    /// Resizes the terminal grid. Use <paramref name="reflow"/> = <see langword="false"/> when
    /// ConPTY performs its own reflow and repaints the viewport.
    /// </summary>
    void Resize(int columns, int rows, bool reflow);

    /// <summary>
    /// Copies a row into caller-owned storage and returns its metadata. Rows are indexed from
    /// zero through <see cref="TotalRows"/> minus one: scrollback first, then the live screen.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="destination"/> is shorter than the row.
    /// </exception>
    TerminalRowInfo CopyRow(int rowIndex, Span<TerminalCell> destination);

    /// <summary>Resolves an OSC 8 hyperlink id from a cell, or returns null when absent.</summary>
    string? GetHyperlink(ushort linkId);
}
