namespace WinMux.Terminal;

/// <summary>
/// WinMux-owned surface over a VT terminal emulator.
/// </summary>
/// <remarks>
/// Implementations are expected to serialize access to their underlying parser. Responses are
/// raised synchronously while <see cref="Write"/> processes terminal output and must be sent back
/// to the PTY so terminal queries do not stall the child process.
/// </remarks>
public interface ITerminalEngine
{
    int Columns { get; }

    int Rows { get; }

    /// <summary>Number of history rows preceding the visible screen.</summary>
    int ScrollbackCount { get; }

    /// <summary>History and visible rows addressable by <see cref="CopyRow"/>.</summary>
    int TotalRows { get; }

    /// <summary>Monotonic grid-change counter for renderer damage tracking.</summary>
    long Version { get; }

    TerminalCursor Cursor { get; }

    string Title { get; }

    bool UsingAlternateScreen { get; }

    /// <summary>
    /// Changes when OSC 8 link identifiers may have been renumbered or discarded.
    /// </summary>
    int HyperlinkGeneration { get; }

    /// <summary>Raised when the terminal grid changes.</summary>
    event Action? Updated;

    /// <summary>Raised when the terminal title changes.</summary>
    event Action<string>? TitleChanged;

    /// <summary>
    /// Bytes generated by terminal queries such as DA, DSR, and DECRQM. The subscriber must
    /// write them back to the PTY. The supplied memory must not be retained after the callback.
    /// </summary>
    event Action<ReadOnlyMemory<byte>>? Response;

    /// <summary>Feeds bytes received from the PTY into the VT parser.</summary>
    void Write(ReadOnlySpan<byte> bytes);

    /// <summary>
    /// Resizes the terminal grid. Use <paramref name="reflow"/> = <see langword="false"/> when
    /// ConPTY performs its own reflow and repaints the viewport.
    /// </summary>
    void Resize(int columns, int rows, bool reflow);

    /// <summary>
    /// Copies a row into caller-owned storage and returns its metadata. Rows are indexed from
    /// zero through <see cref="TotalRows"/> minus one: scrollback first, then the live screen.
    /// </summary>
    /// <exception cref="ArgumentException">
    /// <paramref name="destination"/> is shorter than the row.
    /// </exception>
    TerminalRowInfo CopyRow(int rowIndex, Span<TerminalCell> destination);

    /// <summary>Resolves an OSC 8 hyperlink id from a cell, or returns null when absent.</summary>
    string? GetHyperlink(ushort linkId);
}
